# Generated by Django 6.0.5 on 2026-05-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cierrejornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='dependiente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='mesa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_personas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
