# Generated by Django 6.0.5 on 2026-05-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_dependiente_venta_folio_venta_mesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
