# Generated by Django 6.0.5 on 2026-05-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
    ]
