# Generated by Django 6.0.5 on 2026-05-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_entradaproducto_usuario_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('venta', 'Producto de venta'), ('enlatado', 'Enlatado / directo'), ('ingrediente', 'Ingrediente')], default='venta', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('litro', 'Litro'), ('ml', 'Mililitro'), ('paquete', 'Paquete')], default='unidad', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
