# Generated by Django 6.0.5 on 2026-05-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_tipo_producto_unidad_medida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('lb', 'Libra'), ('litro', 'Litro'), ('ml', 'Mililitro'), ('paquete', 'Paquete')], default='unidad', max_length=20),
        ),
    ]
