# Generated by Django 6.0.5 on 2026-05-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproducto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='stock_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='stock_nuevo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
